import { describe, expect, it, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { dateToWeekDay, weekDayToDate, PILOT_WEEK_1_START } from '../pilot-config.js';
import {
	resolveSlot,
	postIndexForSlot,
	chooseBed,
	computeWallPlainLines,
	scheduleFileName
} from '../cli-plan.js';
import { loadOutputCard } from '../remotion/wall-pool.js';
import { gateObjectionCard } from '../remotion/objection-gate.js';
import { probe, assertMeetsProfile } from '../render/encode.js';
import type { WeekSchedule } from '../schedule-types.js';

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(moduleDir, '..', '..', '..');
const cliPath = path.join(repoRoot, 'social', 'src', 'cli.ts');
const scheduleDir = path.join(repoRoot, 'content', 'social');
const fixturesDir = path.join(moduleDir, 'fixtures');

// --- Real, committed week-1 schedule (generated by
// `npx tsx scripts/generate-schedule.ts --week 1 --seed 42 --first-week`) ---
const WEEK_1_SCHEDULE = JSON.parse(
	readFileSync(path.join(scheduleDir, scheduleFileName(1)), 'utf-8')
) as WeekSchedule;

// --- A TEST FIXTURE, not real pipeline state — see `__tests__/fixtures/
// README.md` for exactly how it was generated (`--objection-weight 20
// --skip-review-check`) and why that disqualifies it from ever being real
// week-2 pipeline state (it bypasses plan 01's review gate and skips
// carrying week 1's reviewed weights forward). F08: week 1 contains no
// Objection slot at all (weight 1, capped at one per week, and week 1's
// draw gave it none), so this fixture exists purely to exercise the
// Objection render path end to end. It lives under `__tests__/fixtures/`,
// not `content/social/`, and is only ever read via `cli.ts`'s
// `--schedule-dir` override (see the Objection describe block below) —
// never by `loadPriorWeeks` or any real week-3 generation. ---
const WEEK_2_SCHEDULE = JSON.parse(
	readFileSync(path.join(fixturesDir, scheduleFileName(2)), 'utf-8')
) as WeekSchedule;

interface RunResult {
	status: number;
	stdout: string;
	stderr: string;
}

function runCli(args: string[]): RunResult {
	try {
		const stdout = execFileSync('npx', ['tsx', cliPath, ...args], {
			cwd: repoRoot,
			encoding: 'utf-8',
			stdio: ['ignore', 'pipe', 'pipe']
		});
		return { status: 0, stdout, stderr: '' };
	} catch (e) {
		const err = e as { status: number | null; stdout: string; stderr: string };
		return { status: err.status ?? 1, stdout: err.stdout ?? '', stderr: err.stderr ?? '' };
	}
}

// ---------------------------------------------------------------------------
// pilot-config.ts — date <-> (week, day) mapping
// ---------------------------------------------------------------------------

describe('dateToWeekDay / weekDayToDate', () => {
	it('PILOT_WEEK_1_START (2026-09-01) maps to week 1, day 1', () => {
		expect(PILOT_WEEK_1_START).toBe('2026-09-01');
		expect(dateToWeekDay('2026-09-01')).toEqual({ week: 1, day: 1 });
	});

	it('day 7 of week 1 is 2026-09-07; day 1 of week 2 is 2026-09-08', () => {
		expect(dateToWeekDay('2026-09-07')).toEqual({ week: 1, day: 7 });
		expect(dateToWeekDay('2026-09-08')).toEqual({ week: 2, day: 1 });
	});

	it('round-trips for a range of dates', () => {
		const dates = ['2026-09-01', '2026-09-02', '2026-09-07', '2026-09-08', '2026-10-15', '2027-01-01'];
		for (const date of dates) {
			const { week, day } = dateToWeekDay(date);
			expect(weekDayToDate(week, day)).toBe(date);
		}
	});

	it('round-trips for a range of (week, day) pairs', () => {
		for (const week of [1, 2, 5, 12]) {
			for (const day of [1, 2, 3, 4, 5, 6, 7]) {
				const date = weekDayToDate(week, day);
				expect(dateToWeekDay(date)).toEqual({ week, day });
			}
		}
	});

	it('errors clearly on a date before the pilot start', () => {
		expect(() => dateToWeekDay('2026-08-31')).toThrow(/before the pilot/i);
	});

	it('errors clearly on a malformed date', () => {
		expect(() => dateToWeekDay('not-a-date')).toThrow(/invalid date/i);
		expect(() => dateToWeekDay('2026-13-40')).toThrow(/invalid date/i);
	});

	it('errors clearly on an out-of-range week/day pair', () => {
		expect(() => weekDayToDate(0, 1)).toThrow(/invalid week/i);
		expect(() => weekDayToDate(1, 0)).toThrow(/invalid day/i);
		expect(() => weekDayToDate(1, 8)).toThrow(/invalid day/i);
	});
});

// ---------------------------------------------------------------------------
// Slot resolution against the real committed week-1 schedule
// ---------------------------------------------------------------------------

describe('resolveSlot — against the real committed week-1 schedule', () => {
	it('2026-09-01 slot 1 resolves to the expected card and format', () => {
		const { week, day } = dateToWeekDay('2026-09-01');
		expect(week).toBe(1);
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 1);
		expect(slot.card_id).toBe('meditations-02-001');
		expect(slot.book_slug).toBe('meditations');
		// F19: under F18's per-card Wall fit, meditations-02-001 (117 words)
		// fits only 3335px even at the font cap, short of the 3400px travel
		// target — so this read-through slot falls all the way through the
		// Wall/Question/Objection cascade to the STILL fallback (see
		// `scripts/lib/schedule.ts`'s `resolveReadThrough`). This is exactly
		// F19's own fix: the slot still renders, "Card 1 of 48" still holds.
		expect(slot.content.format).toBe('still');
		expect(slot.read_through).toBe(true);
		expect(slot.read_through_counter).toBe('Card 1 of 48');
	});

	it('2026-09-01 slot 2 resolves to the expected card and format', () => {
		const { day } = dateToWeekDay('2026-09-01');
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 2);
		expect(slot.card_id).toBe('happy-life-25-001');
		expect(slot.book_slug).toBe('happy-life');
		expect(slot.content.format).toBe('wall');
		expect(slot.read_through).toBe(false);
	});

	it('throws a clear error for a day/slot the schedule has no entry for', () => {
		expect(() => resolveSlot(WEEK_1_SCHEDULE, 99, 1)).toThrow(/day 99/);
	});
});

// ---------------------------------------------------------------------------
// Deterministic bed choice
// ---------------------------------------------------------------------------

describe('chooseBed — deterministic for a given date+slot', () => {
	it('the same postIndex always chooses the same bed', () => {
		const seed = postIndexForSlot('2026-09-01', 1);
		expect(chooseBed(seed).id).toBe(chooseBed(seed).id);
	});

	it('a different (date, slot) pair usually chooses a different postIndex, and consecutive slots never repeat a bed', () => {
		const seedSlot1 = postIndexForSlot('2026-09-01', 1);
		const seedSlot2 = postIndexForSlot('2026-09-01', 2);
		expect(seedSlot2).toBe(seedSlot1 + 1);
		expect(chooseBed(seedSlot1).id).not.toBe(chooseBed(seedSlot2).id);
	});
});

// ---------------------------------------------------------------------------
// computeWallPlainLines
// ---------------------------------------------------------------------------

describe('computeWallPlainLines', () => {
	it('splits out every sentence of plain_english except the landing line, in order', () => {
		// Day 6, slot 1 — a real Wall read-through slot in the committed
		// week-1 schedule whose landing line is a real (non-whole-passage)
		// substring, so there's a non-empty remainder to split (day 2's
		// meditations-02-002 and day 5's meditations-02-005 both land a
		// landing line equal to the ENTIRE plain_english, leaving nothing to
		// split — see F19: day 1's own meditations-02-001 falls through to
		// the Still fallback instead of Wall at all).
		const card = loadOutputCard('meditations', 'meditations-02-006');
		const slot = resolveSlot(WEEK_1_SCHEDULE, 6, 1);
		if (slot.content.format !== 'wall') throw new Error('expected a wall slot');
		const landingLine = slot.content.landing_line;

		const plainLines = computeWallPlainLines(card.plain_english, landingLine);
		expect(plainLines.length).toBeGreaterThan(0);
		expect(plainLines).not.toContain(landingLine);
		for (const line of plainLines) {
			expect(card.plain_english).toContain(line);
		}
	});

	it('throws when the landing line is not a substring of plain_english', () => {
		expect(() => computeWallPlainLines('Some plain text here.', 'Not present anywhere.')).toThrow();
	});
});

// ---------------------------------------------------------------------------
// The CLI process itself
// ---------------------------------------------------------------------------

describe('--dry-run', () => {
	// `outDir` is a nonexistent `out` child of `parentDir` — dry-run never
	// creates it (that's the point of the test), so removing `outDir` alone
	// is a no-op. Track and remove the mkdtemp parent instead, or it leaks.
	let parentDir: string;
	let outDir: string;

	afterEach(async () => {
		if (parentDir) await rm(parentDir, { recursive: true, force: true });
	});

	it('prints the plan and writes nothing', async () => {
		parentDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-dry-'));
		outDir = path.join(parentDir, 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--dry-run']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/meditations-02-001/);
		// F19: day 1's read-through card (meditations-02-001) falls through
		// the cascade to the Still fallback under the real committed week-1
		// schedule — see the `resolveSlot` describe block above.
		expect(result.stdout).toMatch(/Still/);
		expect(result.stdout.toLowerCase()).toMatch(/dry run/);
		expect(existsSync(outDir)).toBe(false);
	});

	// social pilot 02a T13 — the framing layer, extended to the Still
	// composition. The real card's own `source_reference` (never hardcoded)
	// reaches `buildInputProps`/`printPlan` the same way `sourceReference`
	// already did for the Wall (T11/T12) — this is the Still branch of that
	// same wiring. Still never shows a running head (see `Still.tsx`'s own
	// doc comment), so `printPlan` reports "payoff label only", not a
	// resolved running-head string the way the Wall branch does.
	it('threads the real card\'s source_reference through for a Still slot, reporting "payoff label only" (no running head in this format)', async () => {
		parentDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-dry-'));
		outDir = path.join(parentDir, 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--dry-run']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/source reference: "Meditations, Book 2, Section 1"/);
		expect(result.stdout).toMatch(/payoff label only — no running head in this format/);
	});
});

describe('--require-narration', () => {
	// Same reasoning as `--dry-run` above: `outDir` is never created (the
	// render is refused before anything is written), so track and remove
	// the mkdtemp parent, not `outDir` itself.
	let parentDir: string;
	let outDir: string;

	afterEach(async () => {
		if (parentDir) await rm(parentDir, { recursive: true, force: true });
	});

	it('fails loudly instead of rendering a music-only asset', async () => {
		parentDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-narr-'));
		outDir = path.join(parentDir, 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--require-narration']);
		expect(result.status).not.toBe(0);
		expect(result.stderr).toMatch(/T14/);
		expect(result.stderr).toMatch(/require-narration/i);
		expect(existsSync(outDir)).toBe(false);
	});
});

describe('--help', () => {
	it('exits 0 and documents render, --date, --slot', () => {
		const result = runCli(['--help']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/--date/);
		expect(result.stdout).toMatch(/--slot/);
		expect(result.stdout).toMatch(/render/);
	});
});

describe('render — end-to-end: a real MP4, IG feed still, and metadata sidecar', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'produces a house-profile-conformant MP4 (15s-59s), an IG feed JPEG, and a metadata sidecar with narration: false',
		async () => {
			// Day 6, slot 1 of the REAL committed week-1 schedule
			// (meditations-02-006) — a real Wall read-through slot. (F19: day
			// 1's own read-through card, meditations-02-001, falls through the
			// cascade to the Still fallback instead — see the `resolveSlot`
			// describe block above and `render — end-to-end: The Still (F19)`
			// below. Days 2 and 5's own read-through cards, meditations-02-002
			// and meditations-02-005, ALSO fall through to Still under the T02
			// landing-line requirement — their landing lines used to equal the
			// entire plain_english passage under the old whole-passage
			// fallback; see `computeWallPlainLines`'s describe block above.)
			const slot = resolveSlot(WEEK_1_SCHEDULE, 6, 1);
			if (slot.content.format !== 'wall') throw new Error('expected a wall slot');

			const date = weekDayToDate(1, 6);
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-'));

			const result = runCli(['render', '--date', date, '--slot', '1', '--out', outDir]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, `wall-${date}-slot1.mp4`);
			const feedPath = path.join(outDir, `wall-${date}-slot1-feed.jpg`);
			const metadataPath = path.join(outDir, `wall-${date}-slot1.json`);

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe(slot.card_id);
			expect(metadata.format).toBe('wall');
			expect(metadata.narration).toBe(false);
			expect(metadata.rendered_at).toBe(`${date}T00:00:00.000Z`);
			// T17 retired the opening rotation entirely — the sidecar carries
			// no opening field at all, for any format.
			expect(metadata.opening).toBeUndefined();

			const feedBuf = readFileSync(feedPath);
			// JPEG magic bytes.
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});

// ---------------------------------------------------------------------------
// F08 (review M6): The Objection had no end-to-end render coverage at all —
// week 1 contains no Objection slot (weight 1, capped at one per week, and
// week 1's weighted draw gave it none), so `buildInputProps`'s objection
// branch, `Objection.tsx`'s `calculateMetadata` (`gateObjectionCard`),
// `feedStillText`, `narrationPlan`'s `OBJECTION_REPLY_LINE_COUNT` slice and
// the `objection-*.mp4` naming path had never executed together. The week-2
// FIXTURE (`__tests__/fixtures/pilot-schedule-w02.json` — see the
// WEEK_2_SCHEDULE comment above and `fixtures/README.md`) supplies a real
// Objection slot; the CLI is pointed at it via `--schedule-dir` rather than
// reading `content/social/`, which holds only real, reviewed weeks.
// ---------------------------------------------------------------------------

describe('render — end-to-end: The Objection (F08)', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'renders a house-profile-conformant MP4, an IG feed JPEG and a metadata sidecar, with the reply capped ' +
			'to its first two verbatim, terminally-punctuated sentences (the T08 acceptance criterion, proven ' +
			'through the real render path)',
		async () => {
			// Week 2, day 1, slot 2 — the one Objection slot week 2's draw landed.
			const slot = resolveSlot(WEEK_2_SCHEDULE, 1, 2);
			if (slot.content.format !== 'objection') throw new Error('expected an objection slot');
			const { objection, reply } = slot.content;

			// What the gate `Objection.tsx`'s own `calculateMetadata` and
			// `narrationPlan`'s `OBJECTION_REPLY_LINE_COUNT` slice both run —
			// computed here independently of the CLI so the assertions below
			// are checked against a known-good expectation, not derived from
			// whatever the render happened to produce.
			const gated = gateObjectionCard({ objection, reply });
			if (!gated.ok) throw new Error(`fixture objection slot does not pass the gate: ${gated.reason}`);
			for (const line of gated.replyLines) {
				expect(reply).toContain(line);
				expect(line).toMatch(/[.!?]["'”’)\]]*$/);
			}

			const date = weekDayToDate(2, 1);
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-objection-'));

			const result = runCli([
				'render',
				'--date',
				date,
				'--slot',
				'2',
				'--out',
				outDir,
				'--schedule-dir',
				fixturesDir
			]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, `objection-${date}-slot2.mp4`);
			const feedPath = path.join(outDir, `objection-${date}-slot2-feed.jpg`);
			const metadataPath = path.join(outDir, `objection-${date}-slot2.json`);

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe(slot.card_id);
			expect(metadata.format).toBe('objection');
			// T17 retired the opening rotation entirely — no opening field.
			expect(metadata.opening).toBeUndefined();

			const feedBuf = readFileSync(feedPath);
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});

// ---------------------------------------------------------------------------
// The Question — week 1 has four Question slots but, before this, the only
// end-to-end CLI test rendered slot 1 of day 1, a Wall. Adding coverage
// here for the same reason as The Objection above: the Question branch of
// `buildInputProps`, `Question.tsx`'s `calculateMetadata` and its
// answerability gate had never executed through the real CLI render path.
// ---------------------------------------------------------------------------

describe('render — end-to-end: The Question', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'renders a house-profile-conformant MP4, an IG feed JPEG, and a metadata sidecar',
		async () => {
			// Day 2, slot 2 of the REAL committed week-1 schedule
			// (meditations-08-045) — one of the four committed Question slots.
			const slot = resolveSlot(WEEK_1_SCHEDULE, 2, 2);
			if (slot.content.format !== 'question') throw new Error('expected a question slot');

			const date = weekDayToDate(1, 2);
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-question-'));

			const result = runCli(['render', '--date', date, '--slot', '2', '--out', outDir]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, `question-${date}-slot2.mp4`);
			const feedPath = path.join(outDir, `question-${date}-slot2-feed.jpg`);
			const metadataPath = path.join(outDir, `question-${date}-slot2.json`);

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe(slot.card_id);
			expect(metadata.format).toBe('question');
			// T17 retired the opening rotation entirely — no opening field.
			expect(metadata.opening).toBeUndefined();

			const feedBuf = readFileSync(feedPath);
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});

// ---------------------------------------------------------------------------
// The Still (F19) — the read-through's fallback format. `meditations-02-003`
// is one of the exact real cards the plan's own motivating example names
// (58 words, structurally too short to reach the Wall gate's travel target
// even at the font cap — see `content/social/render-exclusions.json`'s
// `read_through` section), and it IS day 3's real committed read-through
// slot in week 1 — this exercises the fallback through the real render path
// end to end, not a synthetic fixture.
// ---------------------------------------------------------------------------

describe('render — end-to-end: The Still (F19)', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'renders a house-profile-conformant MP4, an IG feed JPEG, and a metadata sidecar with format: "still"',
		async () => {
			// Day 3, slot 1 — meditations-02-003, one of the exact cards the
			// plan names as too short to be a Wall.
			const slot = resolveSlot(WEEK_1_SCHEDULE, 3, 1);
			if (slot.content.format !== 'still') throw new Error('expected a still slot');
			expect(slot.card_id).toBe('meditations-02-003');
			const card = loadOutputCard('meditations', 'meditations-02-003');
			// Faithful, verbatim — never trimmed or reworded.
			expect(slot.content.text).toBe(card.plain_english);

			const date = weekDayToDate(1, 3);
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-still-'));

			const result = runCli(['render', '--date', date, '--slot', '1', '--out', outDir]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, `still-${date}-slot1.mp4`);
			const feedPath = path.join(outDir, `still-${date}-slot1-feed.jpg`);
			const metadataPath = path.join(outDir, `still-${date}-slot1.json`);

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe(slot.card_id);
			expect(metadata.format).toBe('still');
			expect(metadata.narration).toBe(false);
			expect(metadata.rendered_at).toBe(`${date}T00:00:00.000Z`);
			// T17 retired the opening rotation entirely — no opening field.
			expect(metadata.opening).toBeUndefined();

			const feedBuf = readFileSync(feedPath);
			// JPEG magic bytes.
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});
