import { describe, expect, it, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { dateToWeekDay, weekDayToDate, PILOT_WEEK_1_START } from '../pilot-config.js';
import {
	resolveSlot,
	postIndexForSlot,
	chooseBed,
	computeWallPlainLines,
	scheduleFileName
} from '../cli-plan.js';
import { loadOutputCard } from '../remotion/wall-pool.js';
import { probe, assertMeetsProfile } from '../render/encode.js';
import type { WeekSchedule } from '../schedule-types.js';

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(moduleDir, '..', '..', '..');
const cliPath = path.join(repoRoot, 'social', 'src', 'cli.ts');
const scheduleDir = path.join(repoRoot, 'content', 'social');

// --- Real, committed week-1 schedule (generated by
// `npx tsx scripts/generate-schedule.ts --week 1 --seed 42 --first-week`) ---
const WEEK_1_SCHEDULE = JSON.parse(
	readFileSync(path.join(scheduleDir, scheduleFileName(1)), 'utf-8')
) as WeekSchedule;

interface RunResult {
	status: number;
	stdout: string;
	stderr: string;
}

function runCli(args: string[]): RunResult {
	try {
		const stdout = execFileSync('npx', ['tsx', cliPath, ...args], {
			cwd: repoRoot,
			encoding: 'utf-8',
			stdio: ['ignore', 'pipe', 'pipe']
		});
		return { status: 0, stdout, stderr: '' };
	} catch (e) {
		const err = e as { status: number | null; stdout: string; stderr: string };
		return { status: err.status ?? 1, stdout: err.stdout ?? '', stderr: err.stderr ?? '' };
	}
}

// ---------------------------------------------------------------------------
// pilot-config.ts — date <-> (week, day) mapping
// ---------------------------------------------------------------------------

describe('dateToWeekDay / weekDayToDate', () => {
	it('PILOT_WEEK_1_START (2026-09-01) maps to week 1, day 1', () => {
		expect(PILOT_WEEK_1_START).toBe('2026-09-01');
		expect(dateToWeekDay('2026-09-01')).toEqual({ week: 1, day: 1 });
	});

	it('day 7 of week 1 is 2026-09-07; day 1 of week 2 is 2026-09-08', () => {
		expect(dateToWeekDay('2026-09-07')).toEqual({ week: 1, day: 7 });
		expect(dateToWeekDay('2026-09-08')).toEqual({ week: 2, day: 1 });
	});

	it('round-trips for a range of dates', () => {
		const dates = ['2026-09-01', '2026-09-02', '2026-09-07', '2026-09-08', '2026-10-15', '2027-01-01'];
		for (const date of dates) {
			const { week, day } = dateToWeekDay(date);
			expect(weekDayToDate(week, day)).toBe(date);
		}
	});

	it('round-trips for a range of (week, day) pairs', () => {
		for (const week of [1, 2, 5, 12]) {
			for (const day of [1, 2, 3, 4, 5, 6, 7]) {
				const date = weekDayToDate(week, day);
				expect(dateToWeekDay(date)).toEqual({ week, day });
			}
		}
	});

	it('errors clearly on a date before the pilot start', () => {
		expect(() => dateToWeekDay('2026-08-31')).toThrow(/before the pilot/i);
	});

	it('errors clearly on a malformed date', () => {
		expect(() => dateToWeekDay('not-a-date')).toThrow(/invalid date/i);
		expect(() => dateToWeekDay('2026-13-40')).toThrow(/invalid date/i);
	});

	it('errors clearly on an out-of-range week/day pair', () => {
		expect(() => weekDayToDate(0, 1)).toThrow(/invalid week/i);
		expect(() => weekDayToDate(1, 0)).toThrow(/invalid day/i);
		expect(() => weekDayToDate(1, 8)).toThrow(/invalid day/i);
	});
});

// ---------------------------------------------------------------------------
// Slot resolution against the real committed week-1 schedule
// ---------------------------------------------------------------------------

describe('resolveSlot — against the real committed week-1 schedule', () => {
	it('2026-09-01 slot 1 resolves to the expected card and format', () => {
		const { week, day } = dateToWeekDay('2026-09-01');
		expect(week).toBe(1);
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 1);
		expect(slot.card_id).toBe('meditations-02-001');
		expect(slot.book_slug).toBe('meditations');
		// Under the regenerated week-1 schedule, meditations-02-001's landing
		// line ("There is only a certain amount of time given to you.") is a
		// genuine substring of its plain_english, not the whole passage — so
		// this read-through slot fits the Wall gate directly and never falls
		// through to the Still fallback (contrast day 2's meditations-02-002
		// and day 5's meditations-02-005 below, whose landing lines equal
		// their ENTIRE plain_english and so do fall through — see
		// `computeWallPlainLines`'s describe block below).
		expect(slot.content.format).toBe('wall');
		expect(slot.read_through).toBe(true);
		expect(slot.read_through_counter).toBe('Card 1 of 48');
	});

	it('2026-09-01 slot 2 resolves to the expected card and format', () => {
		const { day } = dateToWeekDay('2026-09-01');
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 2);
		expect(slot.card_id).toBe('peace-of-mind-17-005');
		expect(slot.book_slug).toBe('peace-of-mind');
		expect(slot.content.format).toBe('wall');
		expect(slot.read_through).toBe(false);
	});

	it('throws a clear error for a day/slot the schedule has no entry for', () => {
		expect(() => resolveSlot(WEEK_1_SCHEDULE, 99, 1)).toThrow(/day 99/);
	});
});

// ---------------------------------------------------------------------------
// Deterministic bed choice
// ---------------------------------------------------------------------------

describe('chooseBed — deterministic for a given date+slot', () => {
	it('the same postIndex always chooses the same bed', () => {
		const seed = postIndexForSlot('2026-09-01', 1);
		expect(chooseBed(seed).id).toBe(chooseBed(seed).id);
	});

	it('a different (date, slot) pair usually chooses a different postIndex, and consecutive slots never repeat a bed', () => {
		const seedSlot1 = postIndexForSlot('2026-09-01', 1);
		const seedSlot2 = postIndexForSlot('2026-09-01', 2);
		expect(seedSlot2).toBe(seedSlot1 + 1);
		expect(chooseBed(seedSlot1).id).not.toBe(chooseBed(seedSlot2).id);
	});
});

// ---------------------------------------------------------------------------
// computeWallPlainLines
// ---------------------------------------------------------------------------

describe('computeWallPlainLines', () => {
	it('splits out every sentence of plain_english except the landing line, in order', () => {
		// Day 6, slot 1 — a real Wall read-through slot in the committed
		// week-1 schedule whose landing line is a real (non-whole-passage)
		// substring, so there's a non-empty remainder to split (day 2's
		// meditations-02-002 and day 5's meditations-02-005 both land a
		// landing line equal to the ENTIRE plain_english, leaving nothing to
		// split, so those two fall through to the Still fallback instead —
		// see `render — end-to-end: The Still (F19)` below. Day 1's own
		// meditations-02-001 has a genuine, non-whole-passage landing line
		// and stays a Wall — see the `resolveSlot` describe block above).
		const card = loadOutputCard('meditations', 'meditations-02-006');
		const slot = resolveSlot(WEEK_1_SCHEDULE, 6, 1);
		if (slot.content.format !== 'wall') throw new Error('expected a wall slot');
		const landingLine = slot.content.landing_line;

		const plainLines = computeWallPlainLines(card.plain_english, landingLine);
		expect(plainLines.length).toBeGreaterThan(0);
		expect(plainLines).not.toContain(landingLine);
		for (const line of plainLines) {
			expect(card.plain_english).toContain(line);
		}
	});

	it('throws when the landing line is not a substring of plain_english', () => {
		expect(() => computeWallPlainLines('Some plain text here.', 'Not present anywhere.')).toThrow();
	});
});

// ---------------------------------------------------------------------------
// The CLI process itself
// ---------------------------------------------------------------------------

describe('--dry-run', () => {
	// `outDir` is a nonexistent `out` child of `parentDir` — dry-run never
	// creates it (that's the point of the test), so removing `outDir` alone
	// is a no-op. Track and remove the mkdtemp parent instead, or it leaks.
	let parentDir: string;
	let outDir: string;

	afterEach(async () => {
		if (parentDir) await rm(parentDir, { recursive: true, force: true });
	});

	it('prints the plan and writes nothing', async () => {
		parentDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-dry-'));
		outDir = path.join(parentDir, 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--dry-run']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/meditations-02-001/);
		// Day 1's read-through card (meditations-02-001) is a genuine Wall
		// slot under the real committed week-1 schedule — see the
		// `resolveSlot` describe block above.
		expect(result.stdout).toMatch(/composition: Wall/);
		expect(result.stdout.toLowerCase()).toMatch(/dry run/);
		expect(existsSync(outDir)).toBe(false);
	});

	// Pf39c2-social-pilot-02a D01: this used to also dry-run a Still slot
	// (day 2, meditations-02-002, whose plain_english has no qualifying
	// landing line) to prove the framing layer's Still branch. Still was
	// deleted outright — the committed week-1 schedule still carries that
	// slot's format as `"still"` until D04 regenerates it, and rendering it
	// now throws (see `buildRenderPlan`'s deprecation branch in `cli.ts`),
	// so there is no "prints the plan" case left to assert for it.
});

describe('--require-narration', () => {
	// Same reasoning as `--dry-run` above: `outDir` is never created (the
	// render is refused before anything is written), so track and remove
	// the mkdtemp parent, not `outDir` itself.
	let parentDir: string;
	let outDir: string;

	afterEach(async () => {
		if (parentDir) await rm(parentDir, { recursive: true, force: true });
	});

	it('fails loudly instead of rendering a music-only asset', async () => {
		parentDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-narr-'));
		outDir = path.join(parentDir, 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--require-narration']);
		expect(result.status).not.toBe(0);
		expect(result.stderr).toMatch(/T14/);
		expect(result.stderr).toMatch(/require-narration/i);
		expect(existsSync(outDir)).toBe(false);
	});
});

describe('--help', () => {
	it('exits 0 and documents render, --date, --slot', () => {
		const result = runCli(['--help']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/--date/);
		expect(result.stdout).toMatch(/--slot/);
		expect(result.stdout).toMatch(/render/);
	});
});

describe('render — end-to-end: a real MP4, IG feed still, and metadata sidecar', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'produces a house-profile-conformant MP4 (15s-59s), an IG feed JPEG, and a metadata sidecar with narration: false',
		async () => {
			// Day 6, slot 1 of the REAL committed week-1 schedule
			// (meditations-02-006) — a real Wall read-through slot. (Days 2 and
			// 5's own read-through cards, meditations-02-002 and
			// meditations-02-005, fall through to the Still fallback instead
			// under the T02 landing-line requirement — their landing lines
			// equal the entire plain_english passage, leaving nothing to split;
			// see `computeWallPlainLines`'s describe block above and
			// `render — end-to-end: The Still (F19)` below. Day 1's own
			// meditations-02-001 stays a Wall — see the `resolveSlot` describe
			// block above.)
			const slot = resolveSlot(WEEK_1_SCHEDULE, 6, 1);
			if (slot.content.format !== 'wall') throw new Error('expected a wall slot');

			const date = weekDayToDate(1, 6);
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-'));

			const result = runCli(['render', '--date', date, '--slot', '1', '--out', outDir]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, `wall-${date}-slot1.mp4`);
			const feedPath = path.join(outDir, `wall-${date}-slot1-feed.jpg`);
			const metadataPath = path.join(outDir, `wall-${date}-slot1.json`);

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe(slot.card_id);
			expect(metadata.format).toBe('wall');
			expect(metadata.narration).toBe(false);
			expect(metadata.rendered_at).toBe(`${date}T00:00:00.000Z`);
			// T17 retired the opening rotation entirely — the sidecar carries
			// no opening field at all, for any format.
			expect(metadata.opening).toBeUndefined();

			const feedBuf = readFileSync(feedPath);
			// JPEG magic bytes.
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});

// ---------------------------------------------------------------------------
// Pf39c2-social-pilot-02a D01: Question, Objection and Still were deleted
// outright — the channel is one Wall a day, drawn from the Wall pool,
// nothing else. This file used to also carry end-to-end render coverage for
// The Objection (F08, against a week-2 fixture schedule), The Question, and
// The Still (F19) — all three describe blocks, and the week-2 fixture
// schedule they used, are gone. The Wall's own end-to-end coverage above is
// unaffected.
// ---------------------------------------------------------------------------
