import { describe, expect, it, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { dateToWeekDay, weekDayToDate, PILOT_WEEK_1_START } from '../pilot-config.js';
import {
	resolveSlot,
	postIndexForSlot,
	chooseWallOpening,
	chooseBed,
	computeWallPlainLines,
	scheduleFileName
} from '../cli-plan.js';
import { computeEligibleOpenings, WALL_OPENINGS } from '../remotion/wall-openings.js';
import { loadOutputCard } from '../remotion/wall-pool.js';
import { probe, assertMeetsProfile } from '../render/encode.js';
import type { WeekSchedule } from '../schedule-types.js';

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(moduleDir, '..', '..', '..');
const cliPath = path.join(repoRoot, 'social', 'src', 'cli.ts');
const scheduleDir = path.join(repoRoot, 'content', 'social');

// --- Real, committed week-1 schedule (generated by
// `npx tsx scripts/generate-schedule.ts --week 1 --seed 42 --first-week`) ---
const WEEK_1_SCHEDULE = JSON.parse(
	readFileSync(path.join(scheduleDir, scheduleFileName(1)), 'utf-8')
) as WeekSchedule;

interface RunResult {
	status: number;
	stdout: string;
	stderr: string;
}

function runCli(args: string[]): RunResult {
	try {
		const stdout = execFileSync('npx', ['tsx', cliPath, ...args], {
			cwd: repoRoot,
			encoding: 'utf-8',
			stdio: ['ignore', 'pipe', 'pipe']
		});
		return { status: 0, stdout, stderr: '' };
	} catch (e) {
		const err = e as { status: number | null; stdout: string; stderr: string };
		return { status: err.status ?? 1, stdout: err.stdout ?? '', stderr: err.stderr ?? '' };
	}
}

// ---------------------------------------------------------------------------
// pilot-config.ts — date <-> (week, day) mapping
// ---------------------------------------------------------------------------

describe('dateToWeekDay / weekDayToDate', () => {
	it('PILOT_WEEK_1_START (2026-09-01) maps to week 1, day 1', () => {
		expect(PILOT_WEEK_1_START).toBe('2026-09-01');
		expect(dateToWeekDay('2026-09-01')).toEqual({ week: 1, day: 1 });
	});

	it('day 7 of week 1 is 2026-09-07; day 1 of week 2 is 2026-09-08', () => {
		expect(dateToWeekDay('2026-09-07')).toEqual({ week: 1, day: 7 });
		expect(dateToWeekDay('2026-09-08')).toEqual({ week: 2, day: 1 });
	});

	it('round-trips for a range of dates', () => {
		const dates = ['2026-09-01', '2026-09-02', '2026-09-07', '2026-09-08', '2026-10-15', '2027-01-01'];
		for (const date of dates) {
			const { week, day } = dateToWeekDay(date);
			expect(weekDayToDate(week, day)).toBe(date);
		}
	});

	it('round-trips for a range of (week, day) pairs', () => {
		for (const week of [1, 2, 5, 12]) {
			for (const day of [1, 2, 3, 4, 5, 6, 7]) {
				const date = weekDayToDate(week, day);
				expect(dateToWeekDay(date)).toEqual({ week, day });
			}
		}
	});

	it('errors clearly on a date before the pilot start', () => {
		expect(() => dateToWeekDay('2026-08-31')).toThrow(/before the pilot/i);
	});

	it('errors clearly on a malformed date', () => {
		expect(() => dateToWeekDay('not-a-date')).toThrow(/invalid date/i);
		expect(() => dateToWeekDay('2026-13-40')).toThrow(/invalid date/i);
	});

	it('errors clearly on an out-of-range week/day pair', () => {
		expect(() => weekDayToDate(0, 1)).toThrow(/invalid week/i);
		expect(() => weekDayToDate(1, 0)).toThrow(/invalid day/i);
		expect(() => weekDayToDate(1, 8)).toThrow(/invalid day/i);
	});
});

// ---------------------------------------------------------------------------
// Slot resolution against the real committed week-1 schedule
// ---------------------------------------------------------------------------

describe('resolveSlot — against the real committed week-1 schedule', () => {
	it('2026-09-01 slot 1 resolves to the expected card and format', () => {
		const { week, day } = dateToWeekDay('2026-09-01');
		expect(week).toBe(1);
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 1);
		expect(slot.card_id).toBe('meditations-02-001');
		expect(slot.book_slug).toBe('meditations');
		expect(slot.content.format).toBe('wall');
		expect(slot.read_through).toBe(true);
		expect(slot.read_through_counter).toBe('Card 1 of 48');
	});

	it('2026-09-01 slot 2 resolves to the expected card and format', () => {
		const { day } = dateToWeekDay('2026-09-01');
		const slot = resolveSlot(WEEK_1_SCHEDULE, day, 2);
		// F05: week 1 was regenerated once the scheduler started consulting the
		// renderer's Wall exclusion list (content/social/wall-exclusions.json) —
		// dropping 59 excluded entries from the Wall pool shifts which index
		// every subsequent weighted draw lands on, so this slot's card changed
		// even though it was never itself excluded.
		expect(slot.card_id).toBe('shortness-of-life-02-004');
		expect(slot.book_slug).toBe('shortness-of-life');
		expect(slot.content.format).toBe('wall');
		expect(slot.read_through).toBe(false);
	});

	it('throws a clear error for a day/slot the schedule has no entry for', () => {
		expect(() => resolveSlot(WEEK_1_SCHEDULE, 99, 1)).toThrow(/day 99/);
	});
});

// ---------------------------------------------------------------------------
// Deterministic opening choice
// ---------------------------------------------------------------------------

describe('chooseWallOpening — deterministic and always eligible', () => {
	const card = loadOutputCard('meditations', 'meditations-02-001');
	const eligible = computeEligibleOpenings(card.original_excerpt, card.plain_english);
	const seed = postIndexForSlot('2026-09-01', 1);

	it('is deterministic for a given date+slot', () => {
		const first = chooseWallOpening(seed, eligible);
		const second = chooseWallOpening(seed, eligible);
		expect(first).toBe(second);
	});

	it('is always one of the card\'s eligible openings', () => {
		const opening = chooseWallOpening(seed, eligible);
		expect(eligible).toContain(opening);
	});

	it('falls back to "standard" (always eligible) when the rotation candidate is not eligible', () => {
		// A seed whose rotateOpening candidate is NOT "standard" (index 1 -> "countdown"),
		// gated against a card only eligible for "standard".
		const opening = chooseWallOpening(1, ['standard']);
		expect(opening).toBe('standard');
	});

	it('every WALL_OPENINGS entry is reachable across a run of consecutive seeds when everything is eligible', () => {
		const seen = new Set(Array.from({ length: WALL_OPENINGS.length }, (_, i) => chooseWallOpening(i, WALL_OPENINGS)));
		expect(seen.size).toBe(WALL_OPENINGS.length);
	});
});

// ---------------------------------------------------------------------------
// Deterministic bed choice
// ---------------------------------------------------------------------------

describe('chooseBed — deterministic for a given date+slot', () => {
	it('the same postIndex always chooses the same bed', () => {
		const seed = postIndexForSlot('2026-09-01', 1);
		expect(chooseBed(seed).id).toBe(chooseBed(seed).id);
	});

	it('a different (date, slot) pair usually chooses a different postIndex, and consecutive slots never repeat a bed', () => {
		const seedSlot1 = postIndexForSlot('2026-09-01', 1);
		const seedSlot2 = postIndexForSlot('2026-09-01', 2);
		expect(seedSlot2).toBe(seedSlot1 + 1);
		expect(chooseBed(seedSlot1).id).not.toBe(chooseBed(seedSlot2).id);
	});
});

// ---------------------------------------------------------------------------
// computeWallPlainLines
// ---------------------------------------------------------------------------

describe('computeWallPlainLines', () => {
	it('splits out every sentence of plain_english except the landing line, in order', () => {
		const card = loadOutputCard('meditations', 'meditations-02-001');
		const slot = resolveSlot(WEEK_1_SCHEDULE, 1, 1);
		if (slot.content.format !== 'wall') throw new Error('expected a wall slot');
		const landingLine = slot.content.landing_line;

		const plainLines = computeWallPlainLines(card.plain_english, landingLine);
		expect(plainLines.length).toBeGreaterThan(0);
		expect(plainLines).not.toContain(landingLine);
		for (const line of plainLines) {
			expect(card.plain_english).toContain(line);
		}
	});

	it('throws when the landing line is not a substring of plain_english', () => {
		expect(() => computeWallPlainLines('Some plain text here.', 'Not present anywhere.')).toThrow();
	});
});

// ---------------------------------------------------------------------------
// The CLI process itself
// ---------------------------------------------------------------------------

describe('--dry-run', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it('prints the plan and writes nothing', async () => {
		outDir = path.join(await mkdtemp(path.join(tmpdir(), 'plain-social-cli-dry-')), 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--dry-run']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/meditations-02-001/);
		expect(result.stdout).toMatch(/Wall/);
		expect(result.stdout.toLowerCase()).toMatch(/dry run/);
		expect(existsSync(outDir)).toBe(false);
	});
});

describe('--require-narration', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it('fails loudly instead of rendering a music-only asset', async () => {
		outDir = path.join(await mkdtemp(path.join(tmpdir(), 'plain-social-cli-narr-')), 'out');

		const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir, '--require-narration']);
		expect(result.status).not.toBe(0);
		expect(result.stderr).toMatch(/T14/);
		expect(result.stderr).toMatch(/require-narration/i);
		expect(existsSync(outDir)).toBe(false);
	});
});

describe('--help', () => {
	it('exits 0 and documents render, --date, --slot', () => {
		const result = runCli(['--help']);
		expect(result.status).toBe(0);
		expect(result.stdout).toMatch(/--date/);
		expect(result.stdout).toMatch(/--slot/);
		expect(result.stdout).toMatch(/render/);
	});
});

describe('render — end-to-end: a real MP4, IG feed still, and metadata sidecar', () => {
	let outDir: string;

	afterEach(async () => {
		if (outDir) await rm(outDir, { recursive: true, force: true });
	});

	it(
		'produces a house-profile-conformant MP4 (15s-59s), an IG feed JPEG, and a metadata sidecar with narration: false',
		async () => {
			outDir = await mkdtemp(path.join(tmpdir(), 'plain-social-cli-e2e-'));

			const result = runCli(['render', '--date', '2026-09-01', '--slot', '1', '--out', outDir]);
			expect(result.status).toBe(0);

			const videoPath = path.join(outDir, 'wall-2026-09-01-slot1.mp4');
			const feedPath = path.join(outDir, 'wall-2026-09-01-slot1-feed.jpg');
			const metadataPath = path.join(outDir, 'wall-2026-09-01-slot1.json');

			expect(existsSync(videoPath)).toBe(true);
			expect(existsSync(feedPath)).toBe(true);
			expect(existsSync(metadataPath)).toBe(true);

			const probeResult = await probe(videoPath);
			expect(() => assertMeetsProfile(probeResult)).not.toThrow();
			expect(probeResult.durationSec ?? 0).toBeGreaterThanOrEqual(15);
			expect(probeResult.durationSec ?? 0).toBeLessThanOrEqual(59);

			const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
			expect(metadata.card_id).toBe('meditations-02-001');
			expect(metadata.format).toBe('wall');
			expect(metadata.narration).toBe(false);
			expect(metadata.rendered_at).toBe('2026-09-01T00:00:00.000Z');
			expect(WALL_OPENINGS).toContain(metadata.opening);

			const feedBuf = readFileSync(feedPath);
			// JPEG magic bytes.
			expect(feedBuf.subarray(0, 2).toString('hex')).toBe('ffd8');
		},
		300_000
	);
});
