/**
 * Social pilot 02 F17: registers the two real faces every composition names
 * (`Wall.tsx`'s `SERIF_STACK`, `Counter.tsx`'s `COUNTER_FONT_STACK`) inside
 * the Remotion bundle itself.
 *
 * Before this module existed, NOTHING registered an `@font-face` anywhere
 * in the browser-side webpack build Remotion actually renders from — the
 * font families were only ever NAMED, never loaded — so every composition
 * silently fell through `SERIF_STACK`'s stack to `Georgia, serif` (and on a
 * Linux render container with no Georgia installed either, straight to a
 * generic system serif). Meanwhile `social/src/render/card.ts` (the
 * Playwright still renderer for the IG feed JPEG) DID base64-embed the real
 * woff2 files — so the JPEG and the MP4 of the same post shipped in two
 * different typefaces.
 *
 * `import './fonts.generated.css'` below is a side-effect import: webpack's
 * default `.css` handling (`style-loader` + `css-loader`, already part of
 * `@remotion/bundler`'s shared config — no `webpackOverride` needed) injects
 * that file's `@font-face` rules into `document.head` as a real `<style>`
 * tag the instant this module evaluates, which happens once, at bundle
 * load, before `RemotionRoot` ever mounts. `fonts.generated.css` itself is
 * generated by `social/scripts/generate-remotion-font-css.ts` from the
 * SAME base64-inlining loader (`social/src/render/fonts.ts`) `card.ts`
 * uses — one loader, two consumers, not two implementations of the same
 * base64-embedding trick.
 *
 * A `@font-face` rule existing in the stylesheet is necessary but not
 * sufficient: the browser only actually fetches/decodes a face's `src` the
 * first time something asks for it, and that decode is asynchronous even
 * for a `data:` URI with no network round-trip. Remotion's `delayRender`/
 * `continueRender` (imported from the top-level `remotion` package, not
 * `remotion/no-react` — this module runs inside the browser bundle) is the
 * documented way to hold frame 0 until an async prerequisite is ready:
 * `delayRender()` here, at module scope, registers the wait before webpack
 * even finishes evaluating `entry.tsx`, and `continueRender()` only fires
 * once BOTH faces report loaded via the Font Loading API
 * (`document.fonts.load`) — so a still captured at frame 0 can never land
 * mid-fallback.
 */

import { continueRender, delayRender } from 'remotion';

import './fonts.generated.css';

// One representative weight/size per face actually used by a composition —
// `document.fonts.load` triggers the browser to fetch+decode that specific
// face if it hasn't already, and a variable font's whole weight axis (`100
// 900`, see `fonts.generated.css`) loads from a single decode, so loading
// any one weight is sufficient to make every weight in the composition's
// actual use available.
const FONT_LOAD_SPECS = [
	// Literata Variable — Wall.tsx's SERIF_STACK, weight 400 (Wall/PayoffLine/Question body text).
	`400 76px 'Literata Variable'`,
	// DM Sans Variable — Counter.tsx's COUNTER_FONT_STACK, weight 500 (the counter itself).
	`500 28px 'DM Sans Variable'`
];

const handle = delayRender('social pilot 02 F17: waiting for Literata/DM Sans to finish loading');

Promise.all(FONT_LOAD_SPECS.map((spec) => document.fonts.load(spec)))
	.then(() => document.fonts.ready)
	.then(() => continueRender(handle))
	.catch((error: unknown) => {
		// Surface the real error rather than silently continuing into a
		// fallback-face render — a swallowed rejection here would recreate
		// exactly the defect this module exists to fix, just one layer down.
		throw error instanceof Error ? error : new Error(String(error));
	});
